#!/usr/bin/env python3
"""Generate an lgfx/M5GFX GFXfont header from a TTF (1-bit, no antialiasing).

Used to embed the webapp's VT323 pixel font so the device UI matches the
web player's default (Dark) skin. Charset: 32..255 (Latin-1 — station and
show titles carry accents). Requires Pillow.

Usage:
  python3 gen_gfxfont.py <ttf> <out.h> <FontBaseName> <size> [<size> ...]
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 255


def build_font(ttf_path: str, size: int, name: str) -> str:
    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    pad = size * 2

    bitmaps = bytearray()
    glyphs = []

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = max(0, round(font.getlength(ch)))

        canvas = Image.new('1', (pad * 3, pad * 3), 0)
        draw = ImageDraw.Draw(canvas)
        draw.fontmode = '1'  # hard threshold — no antialiasing
        try:
            draw.text((pad, pad), ch, font=font, fill=1)  # anchor: left-ascender
        except Exception:
            pass
        bbox = canvas.getbbox()

        if bbox is None:  # blank glyph (space, missing char)
            glyphs.append((len(bitmaps), 0, 0, advance or size // 2, 0, 0))
            continue

        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        x_off = x0 - pad
        y_off = (y0 - pad) - ascent  # from baseline to bitmap top (negative above)

        offset = len(bitmaps)
        px = canvas.load()
        acc, nbits = 0, 0
        for yy in range(y0, y1):
            for xx in range(x0, x1):
                acc = (acc << 1) | (1 if px[xx, yy] else 0)
                nbits += 1
                if nbits == 8:
                    bitmaps.append(acc)
                    acc, nbits = 0, 0
        if nbits:
            bitmaps.append(acc << (8 - nbits))

        glyphs.append((offset, w, h, advance, x_off, y_off))

    y_advance = ascent + descent
    fname = f'{name}_{size}'
    out = []
    out.append(f'// {fname}: {len(bitmaps)} bytes of bitmap, yAdvance {y_advance}')
    out.append(f'static const uint8_t {fname}_bitmaps[] = {{')
    for i in range(0, len(bitmaps), 16):
        out.append('    ' + ', '.join(f'0x{b:02x}' for b in bitmaps[i:i + 16]) + ',')
    out.append('};')
    out.append(f'static lgfx::GFXglyph {fname}_glyphs[] = {{')
    for (offset, w, h, adv, xo, yo), code in zip(glyphs, range(FIRST, LAST + 1)):
        ch = chr(code) if 32 < code < 127 else ''
        out.append(f'    {{ {offset}, {w}, {h}, {adv}, {xo}, {yo} }},  // {code} {ch}')
    out.append('};')
    out.append(f'static const lgfx::GFXfont {fname}('
               f'const_cast<uint8_t*>({fname}_bitmaps), {fname}_glyphs, '
               f'{FIRST}, {LAST}, {y_advance});')
    out.append('')
    return '\n'.join(out)


def main() -> int:
    if len(sys.argv) < 5:
        print(__doc__, file=sys.stderr)
        return 2
    ttf, out_path, name = sys.argv[1], sys.argv[2], sys.argv[3]
    sizes = [int(s) for s in sys.argv[4:]]

    parts = [
        '// GENERATED by scripts/gen_gfxfont.py — do not edit.',
        f'// Source: {ttf.split("/")[-1]}, sizes {sizes}, chars {FIRST}..{LAST}.',
        '#pragma once',
        '',
        '#include <M5GFX.h>',
        '',
        'namespace whfonts {',
        '',
    ]
    for size in sizes:
        parts.append(build_font(ttf, size, name))
    parts.append('}  // namespace whfonts')
    parts.append('')

    with open(out_path, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(parts))
    print(f'{out_path}: {", ".join(f"{name}_{s}" for s in sizes)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
